sudo: false
language: python
python:
  - 3.4
  - 3.5
  - 3.6
env:
  matrix:
    - TOX_ENV=flake8
cache: pip
install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements-dev.txt"
#  - "travis_retry pip install setuptools --upgrade"
#  - "travis_retry pip install tox"
script:
  - pytest
#after_script:
#  - cat .tox/$TOX_ENV/log/*.log