sudo: false
language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
env:
  matrix:
    - TOX_ENV=flake8
cache: pip
install:
  - "travis_retry pip install setuptools --upgrade"
  - "travis_retry pip install tox"
script:
  - tox -e $TOX_ENV
after_script:
  - cat .tox/$TOX_ENV/log/*.log